//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrenos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carro()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int CarroID { get; set; }
        public int MarcaID { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public string Descripción { get; set; }
        public decimal Precio { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PropietarioID { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Propietario Propietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
