//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrenos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participaciones
    {
        public int ParticipaciónID { get; set; }
        public int ClienteID { get; set; }
        public int SubastaID { get; set; }
        public decimal Oferta { get; set; }
        public System.DateTime FechaOferta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Subasta Subasta { get; set; }
    }
}
