//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrenos2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CostaDelSol : DbContext
    {
        public CostaDelSol()
            : base("name=CostaDelSol")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Carro> Carro { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Participaciones> Participaciones { get; set; }
        public virtual DbSet<Posicion> Posicion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Propietario> Propietario { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Subasta> Subasta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terreno> Terreno { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
