//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrenos2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int TransaccionID { get; set; }
        public int ClienteID { get; set; }
        public int EmpleadoID { get; set; }
        public int ProductoID { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
